deploy:
  tags:
    - inventaryfront
  only:
    refs:
      - developement
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -P 22760 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa "cd inventaryfront; git pull && docker rm inventaryfront && docker build . -t inventaryfront && docker run -p 3001:80 -d --name inventaryfront inventaryfront"
