version: "3.8"

services:
  app:
    container_name: inventaryFront-dev
    build:
      context: .
      target: development
    env_file:
      - development.env
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    ports:
      - "3000:5173"
